default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") {5} %>
  username: root
  password: C0r4l1@#
  host: 127.0.0.1
  port: 3306
development:
  <<: *default
  database: virtual_storage_pazzo_development
production:
  <<: *default
  database: virtual_storage_pazzo_production
  username: virtual_storage_pazzo
  password: <%= ENV["VIRTUAL_STORAGE_PAZZO_DATABASE_PASSWORD"] %>
